GET http://127.0.0.1:3001/animals

GET http://127.0.0.1:3001/animals/adffed83-56b5-4c85-9458-ec30a5412e39

POST http://127.0.0.1:3001/animals
Content-Type: application/json

{
  "name": "Lion6",
  "age": 10,
  "color": "yellow",
  "weight": 200.00,
  "type": "mammal",
  "breed": "African Lion",
  "numberOfLegs": 4
}

PATCH http://127.0.0.1:3001/animals/82d6bd4f-29af-46fd-add6-a8c602279d55
Content-Type: application/json

{
  "age": "aoetuhs"
}

DELETE http://127.0.0.1:3001/animals/adffed83-56b5-4c85-9458-ec30a5412e30
Content-Type: application/json

{}
