GET http://127.0.0.1:3001/animals

GET http://127.0.0.1:3001/animals/01aed1dd-83a4-4474-a2f8-85e1aac7c84e

POST http://127.0.0.1:3001/animals
Content-Type: application/json

{
  "name": "Lion9",
  "age": 10,
  "color": "yellow",
  "weight": 200.00,
  "type": "mammal",
  "breed": "African Lion",
  "numberOfLegs": 4
}

PATCH http://127.0.0.1:3001/animals/30c1458e-e5c4-4c09-83ac-2e59b1a4e640
Content-Type: application/json

{
  "age": 123
}

DELETE http://127.0.0.1:3001/animals/30c1458e-e5c4-4c09-83ac-2e59b1a4e640
Content-Type: application/json

{}
